### ISSUE TITLE
Assignment 3 - Integration

### ISSUE THREAD

**Issue by loyhongshenggg** [CS3219-AY2324S1/ay2324s1-course-assessment-g30#26]

**Comment by loyhongshenggg** [comment]
Add role to token (Assignment 3)

**Comment by loyhongshenggg** [comment]
Only maintainers can update or delete uploaded questions

**Comment by NicolasCwy** [comment]
Added endpoint to check role of user

**Comment by benjytan45678** [comment]
Added middleware functions:
1) Retrieve the user role
2) Compare the question uuid to the user uuid (if user is not an admin)
